spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: cass
    password: password
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

rabbitmq:
  pending-proposal:
    credit-analysis: pending-proposal.credit-analysis
  completed-proposal:
    exchange: completed-proposal.exchange